Lightsource/LED monitoring and reporting
aiephys/acq4 pull request #21
Opened 2017-01-13 18:39 UTC by davereid98133

Should be a clean commit with the necessary changes...

2017-01-13 23:17 UTC, campagnola requested changes

2017-01-13 23:17 UTC, campagnola commented on acq4/devices/Camera/Camera.py
> +from acq4.devices.LightSource import LightSource
Looks like this is not used?

2017-01-13 23:17 UTC, campagnola commented on acq4/devices/Camera/Camera.py
> +        if self.scopeDev is not None:
This line is redundant

2017-01-13 23:17 UTC, campagnola commented on acq4/devices/LEDLightSource/LEDLightSource.py
> +        self.ledconfig = config.get('leds', config)
Why `config.get('leds', config)` ?

2017-01-13 23:17 UTC, campagnola commented on acq4/devices/LEDLightSource/LEDLightSource.py
> +            for k, v in conf.iteritems():
No need to iterate over all of the items here--looks like all you are trying to get is the 'channel'.

2017-01-13 23:17 UTC, campagnola commented on acq4/devices/LEDLightSource/LEDLightSource.py
> +    def getLEDState(self):
I'm confused about why getLEDState should emit a signal? Ideally that signal should be emitted when the state actually changes, rather than when the state is checked.

2017-01-13 23:17 UTC, campagnola commented on acq4/devices/LEDLightSource/LEDLightSource.py
> +                    continue
This is dangerous--it makes the output of this method non-deterministic.

2017-01-13 23:17 UTC, campagnola commented on acq4/devices/LightSource/LightSource.py
> +        self.lightsourceconfig = config.get('sources', config)
Same here--I am confused about `config.get('sources', config)` .

2017-01-13 23:17 UTC, campagnola commented on acq4/devices/LightSource/LightSource.py
> +        self.getLEDState()
`getLEDState` is not a method of `LightSource`; it should not be called from here.

2017-01-13 23:17 UTC, campagnola commented on acq4/devices/LightSource/LightSource.py
> +    def lightChanged(self, state):
The code path here gets confusing--`getLightSourceState` calls `getLEDState`, which emits `sigLightChanged`, which is connected to `lightChanged`. Is this necessary?

2017-01-13 23:17 UTC, campagnola commented on acq4/devices/LightSource/LightSource.py
> +            if (name=="leds"):
LightSource is a generic class; it probably should not know anything about "leds".

2017-01-13 23:17 UTC, campagnola commented on acq4/devices/LightSource/LightSource.py
> +                    for key, value in v.iteritems():
It looks like this block from 30-46 basically just copies a few keys from a dict. Can this be condensed?

2017-01-14 00:53 UTC, davereid98133 commented on acq4/devices/Camera/Camera.py
> +from acq4.devices.LightSource import LightSource
Luke...Thanks for the feedback.  I'll go through all this and update with the changes first thing on monday morning.

2017-01-16 19:45 UTC, davereid98133 commented on acq4/devices/LEDLightSource/LEDLightSource.py
> +        self.ledconfig = config.get('leds', config)
I'm trying to get the leds that are defined in the devices.cfg.  The file looks like this:

_LEDs:
    driver: 'LEDLightSource'
    leds:
        blue:
            channel: 'LEDChannels', 'M490L4'
            model: 'Thorlabs.M490L4'
            wavelength: 490*nm
            power: 50*mW
        green:
            channel: 'LEDChannels', 'M530L4'
            model: 'Thorlabs M530L4'
            wavelength: 530*nm
        infrared:
            channel: 'LEDChannels', 'IR1'
            wavelength: 850*nm_

Should I removed the "leds" part, and just go right into the names?

2017-01-16 19:53 UTC, campagnola commented on acq4/devices/LEDLightSource/LEDLightSource.py
> +        self.ledconfig = config.get('leds', config)
I'm confused about why `config` appears twice.

2017-01-16 21:50 UTC, davereid98133 commented on acq4/devices/LEDLightSource/LEDLightSource.py
> +        self.ledconfig = config.get('leds', config)
Ok...I was making the assumption (from looking at other examples), that the second "config" was required in the config.get call.

2017-01-16 22:00 UTC, davereid98133 commented on acq4/devices/LEDLightSource/LEDLightSource.py
> +            for k, v in conf.iteritems():
Ok...fixed...

2017-01-16 22:17 UTC, davereid98133 commented on acq4/devices/LEDLightSource/LEDLightSource.py
> +    def getLEDState(self):
Ok...I've taken out the emit on the getLEDstate.  But is there an appropriate to emit the signal when the state changes without doing the polling for the change in state?  Do I need to add that into the DAQGeneric file?

2017-01-16 22:17 UTC, davereid98133 commented on acq4/devices/LEDLightSource/LEDLightSource.py
> +                    continue
Removed...

2017-01-16 22:31 UTC, campagnola commented on acq4/devices/LEDLightSource/LEDLightSource.py
> +    def getLEDState(self):
There is a signal `DAQGeneric.sigHoldingChanged(channel, value)` that you can connect to.

2017-01-23 19:13 UTC, campagnola commented on acq4/devices/LEDLightSource/LEDLightSource.py
> +            initState = dev.getChannelValue(chan, block=False)
Why `block=False` ?

2017-01-26 20:46 UTC, campagnola requested changes
Getting closer..

2017-01-26 20:46 UTC, campagnola commented on acq4/devices/Camera/Camera.py
> +
remove

2017-01-26 20:46 UTC, campagnola commented on acq4/devices/Camera/Camera.py
> +        info = dict(self.getParams(['binning', 'exposure', 'region', 'triggerMode', 'lightSourceStatus']))
`getParams([..., 'lightSourceStatus'])` won't work. The light state should be in `getScopeState()` below.

2017-01-26 20:46 UTC, campagnola commented on acq4/devices/Camera/Camera.py
> +        self.scopeState['lightSourceState'] = self.lightSource.describe()
`self.scopeState` is protected by a mutex elsewhere; should be done here as well.

2017-01-26 20:46 UTC, campagnola commented on acq4/devices/Camera/Camera.py
> +        with self.lock:
Do you think `self.lightSource` needs to be protected by a mutex? More likely, the `lightSource` methods should be made thread-safe.

2017-01-26 20:46 UTC, campagnola commented on acq4/devices/Camera/Camera.py
> +            lightState = None
This variable is not used.

2017-01-26 20:46 UTC, campagnola commented on acq4/devices/Camera/Camera.py
> +                            'lightSource': lightSourceDescription
Why are `lightSource` and `lightSourceStatus` two separate items in the dict?

2017-01-26 20:46 UTC, campagnola commented on acq4/devices/Camera/Camera.py
> +                    lightSourceStatus = self.dev.getLightState()
Light state should be coming in through `self.dev.getScopeState()`; no need to add another call here.

2017-01-26 20:46 UTC, campagnola commented on acq4/devices/LightSource/LightSource.py
> +            if not isinstance(conf, basestring):
What happens if `conf` is a string? (and why would it be?)

2017-01-26 20:46 UTC, campagnola commented on acq4/devices/LightSource/LightSource.py
> +                desc["description"] = sourceDescription
If I read this correctly, `desc["description"]` just contains a list of multliple references to `desc`.. why?

2017-01-26 20:46 UTC, campagnola commented on acq4/devices/Microscope/Microscope.py
> +        with self.lock:
I don't think we need mutex here..?

2017-01-26 20:46 UTC, campagnola commented on acq4/devices/LightSource/LightSource.py
> +    def describe(self):
In my original suggestion (https://github.com/aiephys/acq4/issues/3#issuecomment-257026585), the `describe()` method would only return information about lights that were currently active. It doesn't _have_ to be that way, but the info stored with images probably doesn't need to describe lamps that are inactive.

2017-01-30 18:52 UTC, davereid98133 commented on acq4/devices/Camera/Camera.py
> +
Removed...

2017-01-30 18:53 UTC, davereid98133 commented on acq4/devices/Camera/Camera.py
> +        info = dict(self.getParams(['binning', 'exposure', 'region', 'triggerMode', 'lightSourceStatus']))
Removed...

2017-01-30 18:55 UTC, davereid98133 commented on acq4/devices/Camera/Camera.py
> +        self.scopeState['lightSourceState'] = self.lightSource.describe()
added a check for the self.lock....

2017-01-30 18:57 UTC, davereid98133 commented on acq4/devices/Camera/Camera.py
> +            lightState = None
removed...

2017-01-30 19:01 UTC, davereid98133 commented on acq4/devices/Camera/Camera.py
> +                            'lightSource': lightSourceDescription
I'm using the lightSourceStatus to indicate the on/off state of the light sources, and the "lightSource" item to give the description (type, power, wavelength, etc) of the light sources.

2017-01-31 00:49 UTC, davereid98133 commented on acq4/devices/Camera/Camera.py
> +        with self.lock:
I'm not sure if it needs to be protected by a mutex.  I was going off of the optomech device as a template.  I'm open to whatever you think is the best way to handle this...

2017-01-31 00:54 UTC, davereid98133 commented
Luke...I've made the recommended changes, but have run into something I'm not sure how to best address.  I'm updating the frameInfo[lightSourceState] every time the DAQ input changes, but the portion of the Camera.py that updates the info[frameInfo] only appears to be called when camera is first turned on.  I get the lightSourceState correctly, but if the DAQ changes with the camera running, I don't pick up that change.  Is there another place the info[frameInfo] gets updated?  Or should I be looking for the method that gets called by the "Save Frame" button to do that update?  Thanks...

2017-01-31 21:03 UTC, campagnola commented
* In `AcquireThread.run()`, information about the current objective is handled here: https://github.com/acq4/acq4/blob/develop/acq4/devices/Camera/Camera.py#L812
* That objective information comes from an earlier call to `Camera.getScopeState()`: https://github.com/acq4/acq4/blob/develop/acq4/devices/Camera/Camera.py#L803
* Meanwhile, the camera keeps a local copy of the microscope state updated by watching for changes to the objective: https://github.com/acq4/acq4/blob/develop/acq4/devices/Camera/Camera.py#L362

So it should be enough to also track light status in `Camera.scopeState` (this is already done here: https://github.com/aiephys/acq4/pull/21/files#diff-f22ca5b93def0c15faf52c0a1c0b4688R375), and add just one more line to `AcquireThread.run()` to access that state (by modifying this line https://github.com/aiephys/acq4/pull/21/files#diff-f22ca5b93def0c15faf52c0a1c0b4688R835).

2017-02-10 22:18 UTC, merged

2017-02-10 22:20 UTC, campagnola commented
Merged! Thanks Dave!
If you're curious, you can see the changes I made this afternoon here: https://github.com/aiephys/acq4/pull/28/commits/82f2547b8881bfd7937361c2918d4613f4ebf58b